### PR TITLE
Backup and restore

### PR DESCRIPTION
**Pull request by metaphore**

### CODE REVIEW

**Comment by metaphore** [comment]
@nielsandriesse @Brice-W 
I think it's stable enough to be tested.

A few notes:
- The backup creation didn't change much on the surface. Same as before it generates a 30-digit passphrase and writes the backup files to the location given by the user (a new backup file deletes the old one).
- "Restore Backup" option was added to the landing screen. On the new screen, the user should select a backup file, enter a passphrase, and after clicking on "Continue" the app will try to process it.
   - Currently, there's no mime-type filter activated for the backup file selection. After some testing, I find it behaves rather unpredictable on older APIs and for now, any files are accepted (*/* mime-type filter).
- After the successful backup restoration, the app should navigate to the home screen with the next things restored for the user:
   - Session ID, recovery phrase, username, and profile picture.
   - The complete conversation list with the entire history of messages and attachments.
   - As for now there's no encryption keys restoration for the private chats, the "session reset" procedure will be initiated for all of them. Once it's complete, the receiving messages will no longer cause "out of sync" errors.
- Backups made prior to this PR won't work in this version due to data incompatibility.
- Also in this version, the actual passphrase format has changed from "00000 00000 00000 00000 00000 00000" to "000000000000000000000000000000". It still displays the same way to the user, but under the hood, the code encrypts backup files using the non-spaced string representation. It's important to note that the users won't be able to enter the old format passphrase into the "Backup Restore" Activity's passphrase text field (it's limited to 30 digits, no spaces allowed).
- Due to the reasons above, the "Backup Enabled" settings flag has been reset and all the users will have to explicitly reactivate them.
- _[Future Case]_ This new backup implementation should also work when the user importing a backup made on an old version of the app (the app has a different (higher) database version), but I didn't test this extensively.

**Comment by Brice-W** [comment]
@metaphore I wanted to start testing it, unfortunately the app crashes when I open the Chats section in the Settings.

**Comment by metaphore** [comment]
@Brice-W
My bad, forgot one little thing doing the final cleanup. Please pull the last commit.

**Comment by Brice-W** [comment]
@metaphore 
I’ve tested a good number of devices & APIs, it worked well on all cases :)
I have a couple of remarks / questions: when I restore from backup, I noticed that the backup setting is disabled in ‘Chats’ settings. If I re-activate it, it gives me a new passphrase and asks me to select a folder, and if I select the folder where the previous backup was stored, it doesn’t delete the old one when the new one is created. Is it possible to keep the passphrase and to erase previous backups when creating new ones?
More generally, settings are not restored, would that be a good idea to include that in backups? @nielsandriesse

**Comment by metaphore** [comment]
Thanks @Brice-W!

> the backup setting is disabled in ‘Chats’ settings.

I forgot to mention this case in the notes. There's nothing wrong with the passphrase, it can be preserved but it's deactivated on purpose...

The reason is when we activate backups we need the user to give us access to the directory to write backups to (using system UI). I guess the common case when users restore a backup would be completely clean Session installation (or data wiped) and in this case, we need to ask them to select the backup dir again in order to reactive the backups. This backup reactivation prompt could be a second step after the backup file is successfully imported. I wasn't sure if we need this feature so I just adopted the simplest and the safest approach.

**Comment by Brice-W** [comment]
Oh okay, I got your point, thanks for the explanation 👍

**Pull request merged**
