### PR TITLE
Re-Enable Safety Numbers

### PR DESCRIPTION
**Pull request by RyanRory**
### First time contributor checklist

- [ ] I have read [how to contribute](https://github.com/signalapp/Signal-Android/blob/master/CONTRIBUTING.md) to this project
- [ ] I have signed the [Contributor License Agreement](https://whispersystems.org/cla/)

### Contributor checklist

- [ ] I am following the [Code Style Guidelines](https://github.com/signalapp/Signal-Android/wiki/Code-Style-Guidelines)
- [ ] I have tested my contribution on these devices:
 * Device A, Android X.Y.Z
 * Device B, Android Z.Y
 * Virtual device W, Android Y.Y.Z
- [ ] My contribution is fully baked and ready to be merged as is
- [ ] I ensure that all the open issues my contribution fixes are mentioned in the commit message of my first commit using the `Fixes #1234` [syntax](https://help.github.com/articles/closing-issues-via-commit-messages/)

----------

### CODE REVIEW

**Comment by Mikunj** [comment]
Nice work, have you tested it to see if the functionality works correctly? We might have broken the functionality while working on the signal backend code.

**Comment by RyanRory** [comment]
> Nice work, have you tested it to see if the functionality works correctly? We might have broken the functionality while working on the signal backend code.

Well, the number shows well and there is a QR code there but I just tried to scan the QR code and nothing happened. So what should it be like when I scan the QR code? Can I just scan it with a system camera and get the safety number?

**Comment by Mikunj** [comment]
> > Nice work, have you tested it to see if the functionality works correctly? We might have broken the functionality while working on the signal backend code.
> 
> Well, the number shows well and there is a QR code there but I just tried to scan the QR code and nothing happened. So what should it be like when I scan the QR code? Can I just scan it with a system camera and get the safety number?

I think scanning the QR code sets that contact to verified.
See: https://support.signal.org/hc/en-us/articles/360007060632-What-is-a-safety-number-and-why-do-I-see-that-it-changed-#safety_number_view

**Comment by RyanRory** [comment]
> > > Nice work, have you tested it to see if the functionality works correctly? We might have broken the functionality while working on the signal backend code.
> > 
> > 
> > Well, the number shows well and there is a QR code there but I just tried to scan the QR code and nothing happened. So what should it be like when I scan the QR code? Can I just scan it with a system camera and get the safety number?
> 
> I think scanning the QR code sets that contact to verified.
> See: https://support.signal.org/hc/en-us/articles/360007060632-What-is-a-safety-number-and-why-do-I-see-that-it-changed-#safety_number_view

Yeah, Kee showed me how this works on Signal yesterday. I am just stuck at the QR coding scanning on iOS. It seems like a delegate method which returns the scanning result has never been called. And I still haven't found out the reason yet.

**Comment by nielsandriesse** [comment]
Let's look at this at a later stage

**Pull request closed without merging**
