### PR TITLE
Use WorkManager API for Background Polling

### PR DESCRIPTION
**Pull request by metaphore**
- `BackgroundPollingJob` is refactored to `BackgroundPollWorker` and utilizes `WorkManager` API for scheduling periodic work.
- That might not particularly fix anything specific but should be a bit more stable with the modern Android background task limitations.

https://trello.com/c/8qmk6ypR/187-use-a-service-for-background-polling

### CODE REVIEW

**Comment by nielsandriesse** [comment]
So I tested this again, and here are the issues I run into:

• I haven't been able to receive messages through background polling, even when I keep the app in the app switcher. On dev it also doesn't work if you kill the app entirely, but it works when you leave the app in the background.
• This branch causes a recurring crash on startup if you already had an old background poll job scheduled (which applies to everyone who had a previous version of the app installed), because it'll try to instantiate the next job and then fail.

**Review by nielsandriesse — CHANGES_REQUESTED** [review]
See my comments above

**Comment by metaphore** [comment]
@nielsandriesse 
I tested it quite a lot on 21-30 API emulators and it's stable enough on my end. Works for foreground, background, and even if the app was swiped from the "recents". It schedules the poll worker on device boot or app startup and persistently triggers it once per 15-20 min (we cannot go more frequently than that due to the API limitations).

It obviously will stop working if the app is forcefully killed entirely until app restart, but that's fine in our case and complies with Android guidelines.

> This branch causes a recurring crash on startup if you already had an old background poll job scheduled

I cleaned up the related DB records so it no longer should be a problem. The case is pretty rare though, because background polling is almost always an instant operation and rarely stays in the job queue on startup.

One thing I noticed is sometimes when there are obviously some messages pending for the device to receive it may require multiple polling attempts to discover those. I tried to troubleshoot that but had no luck and there's absolutely nothing in the logs. I don't think it has anything to do with this PR, as the polling code is exactly the same as it was before. Sounds more like a problem somewhere down deep in the communication protocol.

@Brice-W can I ask you to test it on a variety of devices with the "fast notification strategy" turned off? Just please be patient, it may take up to 30min to get all the messages if the app is in the background :)

**Comment by Brice-W** [comment]
@metaphore I tested as good number of devices & APIs, background, foreground.
It can take its time like you said, but notifications end up coming in.

**Comment by metaphore** [comment]
@nielsandriesse any chance this will be merged soon?

**Pull request merged**
